Backend cleanup nullable warnings and object cycle
it-minds/itm_baboon-squad-todo pull request #12
Opened 2022-09-13 08:54 UTC by Nicolai-Bak

2022-09-13 10:57 UTC, LandSprutte requested changes

2022-09-13 10:57 UTC, LandSprutte commented on todo-frontend-angular/src/app/todo/TodoModel.ts
> +   // subtasks?: SubtaskModel[];
skal de ikke med? :)

2022-09-13 10:57 UTC, LandSprutte commented on todo-frontend-angular/src/app/todo/todolist/todolist.component.ts
> +    this.todoService.getTodos().subscribe(response=>{this.todos=response ; console.log(this.todos)})
husk at fjerne logs inden de går i prod :)

2022-09-13 10:57 UTC, LandSprutte commented on todo-frontend-angular/src/app/todo/todolist/todolist.component.ts
>      console.log('click')
samme gælder her :)

2022-09-14 06:10 UTC, Nicolai-Bak commented on todo-frontend-angular/src/app/todo/TodoModel.ts
> +   // subtasks?: SubtaskModel[];
Gammel model, fil slettet og erstattes af todo.model.ts

2022-09-14 06:28 UTC, LandSprutte approved these changes

2022-09-14 07:19 UTC, AntonEsbjergIT-Minds reviewed
Looks great, godt cleanup, og dejligt med ændring sådan vi ikke får JSON retur men et DTO objekt.

2022-09-14 07:19 UTC, AntonEsbjergIT-Minds approved these changes
Jeg skrev mit review som en kommentar, se den.

2022-09-14 07:19 UTC, merged